CREATE TABLE [dbo].[CATEGORIA]
(
	[IDCATEGORIA] INT IDENTITY (1, 1) NOT NULL PRIMARY KEY, 
    [NOME] NVARCHAR(200) NOT NULL, 
    [DESCRICAO] NVARCHAR(200) NOT NULL
)

GO

CREATE INDEX [IX_CATEGORIA_IDCATEGORIA] ON [dbo].[CATEGORIA] ([IDCATEGORIA])
