CREATE TABLE [dbo].[CONTATO]
(
	[IDCONTATO] INT NOT NULL PRIMARY KEY,
	[NOME] NVARCHAR(200) NOT NULL,
	[APELIDO] NVARCHAR(200) NOT NULL,
	[CPF] NVARCHAR(200) NOT NULL,
	[RG] NVARCHAR(200),
	[TIPO] CHAR NOT NULL,
	[PROFISSAO] NVARCHAR(200) NOT NULL,
	[DATANASCIMENTO] DATE,
	[SEXO] NVARCHAR(200),
	[OBSERVACAO] NVARCHAR(MAX),
	[ATIVO] BIT NOT NULL
)
