CREATE TABLE [dbo].[ENDERECO]
(
	[IDENDERECO] INT IDENTITY (1, 1) NOT NULL PRIMARY KEY,
	[IDCONTATO] INT NOT NULL,
	[LOGRADOURO] NVARCHAR(200) NOT NULL,
	[UF] CHAR(2) NOT NULL,
	[BAIRRO] NVARCHAR(200) NOT NULL,
	[COMPLEMENTO] NVARCHAR(200) NULL, 
    CONSTRAINT [FK_ENDERECO_CONTATO] FOREIGN KEY ([IDCONTATO]) REFERENCES [CONTATO]([IDCONTATO])
)

GO

CREATE INDEX [IX_ENDERECO_IDENDERECO] ON [dbo].[ENDERECO] ([IDENDERECO])
