CREATE TABLE [dbo].[ENDERECO]
(
	[IDENDERECO] INT NOT NULL PRIMARY KEY,
	[IDCONTATO] INT NOT NULL,
	[LOGRADOURO] NVARCHAR(200) NOT NULL,
	[UF] CHAR(2) NOT NULL,
	[BAIRRO] NVARCHAR(200) NOT NULL,
	[COMPLEMENTO] NVARCHAR(200) NOT NULL, 
    CONSTRAINT [FK_ENDERECO_CONTATO] FOREIGN KEY ([IDCONTATO]) REFERENCES [CONTATO]([IDCONTATO])
)
