CREATE TABLE [dbo].[MARCA]
(
	[IDMARCA] INT IDENTITY (1, 1) NOT NULL PRIMARY KEY, 
    [NOME] NVARCHAR(200) NOT NULL, 
    [DESCRICAO] NVARCHAR(200) NOT NULL
)

GO

CREATE INDEX [IX_MARCA_IDMARCA] ON [dbo].[MARCA] ([IDMARCA])
