CREATE TABLE [dbo].[PECA]
(
	[IDPRODUTO] INT NOT NULL PRIMARY KEY, 
    [DESCRICAO] NVARCHAR(13) NOT NULL, 
    [CODIGOBARRAS] NUMERIC(18, 2) NOT NULL, 
    [IDCATEGORIA] INT NOT NULL, 
    [IDMARCA] INT NOT NULL DEFAULT 0, 
    [OBSERVACAO] NVARCHAR(200) NULL, 
    [ATIVO] BIT NOT NULL DEFAULT 1, 
    CONSTRAINT [FK_PECA_CATEGORIA] FOREIGN KEY ([IDCATEGORIA]) REFERENCES [CATEGORIA]([IDCATEGORIA]), 
    CONSTRAINT [FK_PECA_MARCA] FOREIGN KEY ([IDMARCA]) REFERENCES [MARCA](IDMARCA) 
)
