CREATE TABLE [dbo].[PRODUTO]
(
	[IDPRODUTO] INT NOT NULL PRIMARY KEY, 
    [DESCRICAO] NVARCHAR(200) NOT NULL, 
    [CODIGOBARRAS] NVARCHAR(100) NOT NULL, 
    [IDCATEGORIA] INT NOT NULL, 
    [IDMARCA] INT NOT NULL DEFAULT 0,
    [VALORCUSTO] DECIMAL(18,2) NOT NULL,
    [VALORVENDA] DECIMAL(18,2) NOT NULL,
    [LUCRO] DECIMAL(3,2) NOT NULL DEFAULT 0,
    [OBSERVACAO] NVARCHAR(200) NULL, 
    [ATIVO] BIT NOT NULL DEFAULT 1, 
    CONSTRAINT [FK_PRODUTO_CATEGORIA] FOREIGN KEY ([IDCATEGORIA]) REFERENCES [CATEGORIA]([IDCATEGORIA]), 
    CONSTRAINT [FK_PRODUTO_MARCA] FOREIGN KEY ([IDMARCA]) REFERENCES [MARCA](IDMARCA) 
)
