CREATE TABLE [dbo].[PRODUTOVENDA]
(
	[IDVENDA] INT NOT NULL PRIMARY KEY, 
    [IDPRODUTO] INT NOT NULL, 
    [QUANTIDADE] INT NOT NULL, 
    [DESCONTO] DECIMAL(3, 2) NOT NULL, 
    [VALORFINAL] DECIMAL(18, 2) NULL, 
    CONSTRAINT [FK_PRODUTOVENDA_VENDA] FOREIGN KEY ([IDVENDA]) REFERENCES [VENDA]([IDVENDA]), 
    CONSTRAINT [FK_PRODUTOVENDA_PRODUTO] FOREIGN KEY (IDPRODUTO) REFERENCES [PRODUTO]([IDPRODUTO])
)
