CREATE TABLE [dbo].[PRODUTOVENDA]
(
	[IDVENDA] INT NOT NULL, 
    [IDPRODUTO] INT NOT NULL, 
    [QUANTIDADE] INT NOT NULL, 
    [DESCONTO] FLOAT NOT NULL, 
    [VALORFINAL] FLOAT NULL, 
    [IDPRODUTOVENDA] INT NOT NULL PRIMARY KEY IDENTITY (1, 1), 
    CONSTRAINT [FK_PRODUTOVENDA_VENDA] FOREIGN KEY ([IDVENDA]) REFERENCES [VENDA]([IDVENDA]), 
    CONSTRAINT [FK_PRODUTOVENDA_PRODUTO] FOREIGN KEY (IDPRODUTO) REFERENCES [PRODUTO]([IDPRODUTO])
)
