CREATE TABLE [dbo].[PRODUTO]
(
	[IDPRODUTO] INT IDENTITY (1, 1) NOT NULL PRIMARY KEY, 
    [DESCRICAO] NVARCHAR(200) NOT NULL, 
    [CODIGOBARRAS] NVARCHAR(100) NOT NULL, 
    [IDCATEGORIA] INT NOT NULL, 
    [IDMARCA] INT NOT NULL ,
    [VALORCUSTO] DECIMAL(18,2) NOT NULL,
    [VALORVENDA] DECIMAL(18,5) NOT NULL,
    [ESTOQUEMINIMO] INT DEFAULT 0,
    [ESTOQUEMAXIMO] INT DEFAULT 0,
    [LUCRO] DECIMAL(3,2) NULL ,
    [OBSERVACAO] NVARCHAR(200) NULL, 
    [ATIVO] BIT NOT NULL DEFAULT 1, 
    CONSTRAINT [FK_PRODUTO_CATEGORIA] FOREIGN KEY ([IDCATEGORIA]) REFERENCES [CATEGORIA]([IDCATEGORIA]), 
    CONSTRAINT [FK_PRODUTO_MARCA] FOREIGN KEY ([IDMARCA]) REFERENCES [MARCA](IDMARCA) 
)

GO

CREATE INDEX [IX_PRODUTO_IDPRODUTO] ON [dbo].[PRODUTO] ([IDPRODUTO])
