CREATE TABLE [dbo].[TELEFONE]
(
	[IDTELEFONE] INT IDENTITY (1, 1) NOT NULL PRIMARY KEY,
	[IDCONTATO] INT NOT NULL,
	[TIPO] NVARCHAR(200) NULL,
	[NUMERO] NVARCHAR(13) NOT NULL, 
    CONSTRAINT [FK_TELEFONE_CONTATO] FOREIGN KEY ([IDCONTATO]) REFERENCES [CONTATO]([IDCONTATO])
)

GO

CREATE INDEX [IX_TELEFONE_IDTELEFONE] ON [dbo].[TELEFONE] ([IDTELEFONE])
