CREATE TABLE [dbo].[USUARIO]
(
	[ID] INT NOT NULL PRIMARY KEY IDENTITY,
	[NOME] VARCHAR(100) NOT NULL,
	[USUARIO] VARCHAR(20) NOT NULL,
	[SENHA] VARCHAR(50) NOT NULL,
	[ATIVO] BIT NOT NULL DEFAULT 1, 
    [PERMISSAO] BIT NOT NULL DEFAULT 0
)
