CREATE TABLE [dbo].[VENDA]
(
	[IDVENDA] INT NOT NULL  IDENTITY(1,1) PRIMARY KEY, 
    [IDCONTATO] INT NOT NULL, 
    [STATUS] BIT NOT NULL, 
    [DATACRIACAO] DATETIME NOT NULL, 
    [DATAFINALIZACAO] DATETIME NOT NULL, 
    [DESCONTO] DECIMAL(18, 2) NOT NULL, 
    [ATIVO] BIT NOT NULL DEFAULT 1, 
    CONSTRAINT [FK_VENDA_CONTATO] FOREIGN KEY ([IDCONTATO]) REFERENCES [CONTATO]([IDCONTATO])
)
