CREATE TABLE [dbo].[VENDA]
(
	[IDVENDA] INT NOT NULL  IDENTITY(1,1) PRIMARY KEY, 
    [IDCONTATO] INT NOT NULL, 
    [STATUS] INT NOT NULL, 
    [DATACRIACAO] DATETIME NOT NULL, 
    [DATAFINALIZACAO] DATETIME NOT NULL, 
    [DESCONTO] FLOAT NOT NULL DEFAULT 0, 
    [VALOR] FLOAT NOT NULL, 
    CONSTRAINT [FK_VENDA_CONTATO] FOREIGN KEY ([IDCONTATO]) REFERENCES [CONTATO]([IDCONTATO])
)
